// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/configure/configure/configure_configure_server.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Configure_GetConfigure_FullMethodName = "/configure.api_configure.configure.v1.Configure/GetConfigure"
)

// ConfigureClient is the client API for Configure service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigureClient interface {
	GetConfigure(ctx context.Context, in *GetConfigureRequest, opts ...grpc.CallOption) (*GetConfigureReply, error)
}

type configureClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigureClient(cc grpc.ClientConnInterface) ConfigureClient {
	return &configureClient{cc}
}

func (c *configureClient) GetConfigure(ctx context.Context, in *GetConfigureRequest, opts ...grpc.CallOption) (*GetConfigureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigureReply)
	err := c.cc.Invoke(ctx, Configure_GetConfigure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigureServer is the server API for Configure service.
// All implementations must embed UnimplementedConfigureServer
// for forward compatibility.
type ConfigureServer interface {
	GetConfigure(context.Context, *GetConfigureRequest) (*GetConfigureReply, error)
	mustEmbedUnimplementedConfigureServer()
}

// UnimplementedConfigureServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigureServer struct{}

func (UnimplementedConfigureServer) GetConfigure(context.Context, *GetConfigureRequest) (*GetConfigureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigure not implemented")
}
func (UnimplementedConfigureServer) mustEmbedUnimplementedConfigureServer() {}
func (UnimplementedConfigureServer) testEmbeddedByValue()                   {}

// UnsafeConfigureServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigureServer will
// result in compilation errors.
type UnsafeConfigureServer interface {
	mustEmbedUnimplementedConfigureServer()
}

func RegisterConfigureServer(s grpc.ServiceRegistrar, srv ConfigureServer) {
	// If the following call pancis, it indicates UnimplementedConfigureServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Configure_ServiceDesc, srv)
}

func _Configure_GetConfigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigureServer).GetConfigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Configure_GetConfigure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigureServer).GetConfigure(ctx, req.(*GetConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Configure_ServiceDesc is the grpc.ServiceDesc for Configure service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Configure_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configure.api_configure.configure.v1.Configure",
	HandlerType: (*ConfigureServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfigure",
			Handler:    _Configure_GetConfigure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/configure/configure/configure_configure_server.proto",
}
