// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/configure/configure/configure_configure_server.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_configure_configure_configure_configure_server_proto protoreflect.FileDescriptor

const file_api_configure_configure_configure_configure_server_proto_rawDesc = "" +
	"\n" +
	"8api/configure/configure/configure_configure_server.proto\x12$configure.api_configure.configure.v1\x1a1api/configure/configure/configure_configure.proto\x1a\x1cgoogle/api/annotations.proto2\xb5\x01\n" +
	"\tConfigure\x12\xa7\x01\n" +
	"\fGetConfigure\x129.configure.api_configure.configure.v1.GetConfigureRequest\x1a7.configure.api_configure.configure.v1.GetConfigureReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/configure/api/v1/configureB1\n" +
	"\x1aconfigure.api.configure.v1B\bServerV1P\x01Z\a./v1;v1b\x06proto3"

var file_api_configure_configure_configure_configure_server_proto_goTypes = []any{
	(*GetConfigureRequest)(nil), // 0: configure.api_configure.configure.v1.GetConfigureRequest
	(*GetConfigureReply)(nil),   // 1: configure.api_configure.configure.v1.GetConfigureReply
}
var file_api_configure_configure_configure_configure_server_proto_depIdxs = []int32{
	0, // 0: configure.api_configure.configure.v1.Configure.GetConfigure:input_type -> configure.api_configure.configure.v1.GetConfigureRequest
	1, // 1: configure.api_configure.configure.v1.Configure.GetConfigure:output_type -> configure.api_configure.configure.v1.GetConfigureReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_configure_configure_configure_configure_server_proto_init() }
func file_api_configure_configure_configure_configure_server_proto_init() {
	if File_api_configure_configure_configure_configure_server_proto != nil {
		return
	}
	file_api_configure_configure_configure_configure_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_configure_configure_configure_configure_server_proto_rawDesc), len(file_api_configure_configure_configure_configure_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_configure_configure_configure_configure_server_proto_goTypes,
		DependencyIndexes: file_api_configure_configure_configure_configure_server_proto_depIdxs,
	}.Build()
	File_api_configure_configure_configure_configure_server_proto = out.File
	file_api_configure_configure_configure_configure_server_proto_goTypes = nil
	file_api_configure_configure_configure_configure_server_proto_depIdxs = nil
}
