// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: api/configure/configure/configure_configure_server.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationConfigureGetConfigure = "/configure.api_configure.configure.v1.Configure/GetConfigure"

type ConfigureHTTPServer interface {
	GetConfigure(context.Context, *GetConfigureRequest) (*GetConfigureReply, error)
}

func RegisterConfigureHTTPServer(s *http.Server, srv ConfigureHTTPServer) {
	r := s.Route("/")
	r.GET("/configure/api/v1/configure", _Configure_GetConfigure0_HTTP_Handler(srv))
}

func _Configure_GetConfigure0_HTTP_Handler(srv ConfigureHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetConfigureRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConfigureGetConfigure)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetConfigure(ctx, req.(*GetConfigureRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetConfigureReply)
		return ctx.Result(200, reply)
	}
}

type ConfigureHTTPClient interface {
	GetConfigure(ctx context.Context, req *GetConfigureRequest, opts ...http.CallOption) (rsp *GetConfigureReply, err error)
}

type ConfigureHTTPClientImpl struct {
	cc *http.Client
}

func NewConfigureHTTPClient(client *http.Client) ConfigureHTTPClient {
	return &ConfigureHTTPClientImpl{client}
}

func (c *ConfigureHTTPClientImpl) GetConfigure(ctx context.Context, in *GetConfigureRequest, opts ...http.CallOption) (*GetConfigureReply, error) {
	var out GetConfigureReply
	pattern := "/configure/api/v1/configure"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConfigureGetConfigure))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
