// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/configure/configure/configure_configure.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      uint32                 `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	EnvId         uint32                 `protobuf:"varint,2,opt,name=envId,proto3" json:"envId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigureRequest) Reset() {
	*x = GetConfigureRequest{}
	mi := &file_api_configure_configure_configure_configure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigureRequest) ProtoMessage() {}

func (x *GetConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_configure_configure_configure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigureRequest.ProtoReflect.Descriptor instead.
func (*GetConfigureRequest) Descriptor() ([]byte, []int) {
	return file_api_configure_configure_configure_configure_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigureRequest) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *GetConfigureRequest) GetEnvId() uint32 {
	if x != nil {
		return x.EnvId
	}
	return 0
}

type GetConfigureReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId      uint32                 `protobuf:"varint,2,opt,name=serverId,proto3" json:"serverId,omitempty"`
	EnvId         uint32                 `protobuf:"varint,3,opt,name=envId,proto3" json:"envId,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Format        string                 `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	CreatedAt     uint32                 `protobuf:"varint,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigureReply) Reset() {
	*x = GetConfigureReply{}
	mi := &file_api_configure_configure_configure_configure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigureReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigureReply) ProtoMessage() {}

func (x *GetConfigureReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_configure_configure_configure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigureReply.ProtoReflect.Descriptor instead.
func (*GetConfigureReply) Descriptor() ([]byte, []int) {
	return file_api_configure_configure_configure_configure_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigureReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetConfigureReply) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *GetConfigureReply) GetEnvId() uint32 {
	if x != nil {
		return x.EnvId
	}
	return 0
}

func (x *GetConfigureReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetConfigureReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetConfigureReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetConfigureReply) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GetConfigureReply) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_api_configure_configure_configure_configure_proto protoreflect.FileDescriptor

const file_api_configure_configure_configure_configure_proto_rawDesc = "" +
	"\n" +
	"1api/configure/configure/configure_configure.proto\x12$configure.api_configure.configure.v1\x1a\x17validate/validate.proto\"Y\n" +
	"\x13GetConfigureRequest\x12#\n" +
	"\bserverId\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\bserverId\x12\x1d\n" +
	"\x05envId\x18\x02 \x01(\rB\a\xfaB\x04*\x02 \x00R\x05envId\"\xe1\x01\n" +
	"\x11GetConfigureReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bserverId\x18\x02 \x01(\rR\bserverId\x12\x14\n" +
	"\x05envId\x18\x03 \x01(\rR\x05envId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\x12\x1c\n" +
	"\tcreatedAt\x18\b \x01(\rR\tcreatedAtB1\n" +
	"\x1aconfigure.api.configure.v1B\bServerV1P\x01Z\a./v1;v1b\x06proto3"

var (
	file_api_configure_configure_configure_configure_proto_rawDescOnce sync.Once
	file_api_configure_configure_configure_configure_proto_rawDescData []byte
)

func file_api_configure_configure_configure_configure_proto_rawDescGZIP() []byte {
	file_api_configure_configure_configure_configure_proto_rawDescOnce.Do(func() {
		file_api_configure_configure_configure_configure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_configure_configure_configure_configure_proto_rawDesc), len(file_api_configure_configure_configure_configure_proto_rawDesc)))
	})
	return file_api_configure_configure_configure_configure_proto_rawDescData
}

var file_api_configure_configure_configure_configure_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_configure_configure_configure_configure_proto_goTypes = []any{
	(*GetConfigureRequest)(nil), // 0: configure.api_configure.configure.v1.GetConfigureRequest
	(*GetConfigureReply)(nil),   // 1: configure.api_configure.configure.v1.GetConfigureReply
}
var file_api_configure_configure_configure_configure_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_configure_configure_configure_configure_proto_init() }
func file_api_configure_configure_configure_configure_proto_init() {
	if File_api_configure_configure_configure_configure_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_configure_configure_configure_configure_proto_rawDesc), len(file_api_configure_configure_configure_configure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_configure_configure_configure_configure_proto_goTypes,
		DependencyIndexes: file_api_configure_configure_configure_configure_proto_depIdxs,
		MessageInfos:      file_api_configure_configure_configure_configure_proto_msgTypes,
	}.Build()
	File_api_configure_configure_configure_configure_proto = out.File
	file_api_configure_configure_configure_configure_proto_goTypes = nil
	file_api_configure_configure_configure_configure_proto_depIdxs = nil
}
