// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/configure/user/configure_user_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_configure_user_configure_user_service_proto protoreflect.FileDescriptor

const file_api_configure_user_configure_user_service_proto_rawDesc = "" +
	"\n" +
	"/api/configure/user/configure_user_service.proto\x12\x1fconfigure.api.configure.user.v1\x1a'api/configure/user/configure_user.proto\x1a\x1cgoogle/api/annotations.proto2\xb7\x02\n" +
	"\x04User\x12\x87\x01\n" +
	"\x05Login\x12-.configure.api.configure.user.v1.LoginRequest\x1a+.configure.api.configure.user.v1.LoginReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/configure/api/v1/login\x12\xa4\x01\n" +
	"\fRefreshToken\x124.configure.api.configure.user.v1.RefreshTokenRequest\x1a2.configure.api.configure.user.v1.RefreshTokenReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/configure/api/v1/token/refreshB4\n" +
	"\x1fconfigure.api.configure.user.v1B\x06UserV1P\x01Z\a./v1;v1b\x06proto3"

var file_api_configure_user_configure_user_service_proto_goTypes = []any{
	(*LoginRequest)(nil),        // 0: configure.api.configure.user.v1.LoginRequest
	(*RefreshTokenRequest)(nil), // 1: configure.api.configure.user.v1.RefreshTokenRequest
	(*LoginReply)(nil),          // 2: configure.api.configure.user.v1.LoginReply
	(*RefreshTokenReply)(nil),   // 3: configure.api.configure.user.v1.RefreshTokenReply
}
var file_api_configure_user_configure_user_service_proto_depIdxs = []int32{
	0, // 0: configure.api.configure.user.v1.User.Login:input_type -> configure.api.configure.user.v1.LoginRequest
	1, // 1: configure.api.configure.user.v1.User.RefreshToken:input_type -> configure.api.configure.user.v1.RefreshTokenRequest
	2, // 2: configure.api.configure.user.v1.User.Login:output_type -> configure.api.configure.user.v1.LoginReply
	3, // 3: configure.api.configure.user.v1.User.RefreshToken:output_type -> configure.api.configure.user.v1.RefreshTokenReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_configure_user_configure_user_service_proto_init() }
func file_api_configure_user_configure_user_service_proto_init() {
	if File_api_configure_user_configure_user_service_proto != nil {
		return
	}
	file_api_configure_user_configure_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_configure_user_configure_user_service_proto_rawDesc), len(file_api_configure_user_configure_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_configure_user_configure_user_service_proto_goTypes,
		DependencyIndexes: file_api_configure_user_configure_user_service_proto_depIdxs,
	}.Build()
	File_api_configure_user_configure_user_service_proto = out.File
	file_api_configure_user_configure_user_service_proto_goTypes = nil
	file_api_configure_user_configure_user_service_proto_depIdxs = nil
}
