// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/configure/errors/configure_error_reason.proto

package errors

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_ParamsError                 ErrorReason = 0
	ErrorReason_DatabaseError               ErrorReason = 1
	ErrorReason_TransformError              ErrorReason = 2
	ErrorReason_GetError                    ErrorReason = 3
	ErrorReason_ListError                   ErrorReason = 4
	ErrorReason_CreateError                 ErrorReason = 5
	ErrorReason_ImportError                 ErrorReason = 6
	ErrorReason_ExportError                 ErrorReason = 7
	ErrorReason_UpdateError                 ErrorReason = 8
	ErrorReason_DeleteError                 ErrorReason = 9
	ErrorReason_GetTrashError               ErrorReason = 10
	ErrorReason_ListTrashError              ErrorReason = 11
	ErrorReason_DeleteTrashError            ErrorReason = 12
	ErrorReason_RevertTrashError            ErrorReason = 13
	ErrorReason_BusinessValueTypeError      ErrorReason = 14
	ErrorReason_ResourceValueTypeError      ErrorReason = 15
	ErrorReason_RenderTemplateError         ErrorReason = 16
	ErrorReason_TemplateVersionExistError   ErrorReason = 17
	ErrorReason_ServerNotExistTemplateError ErrorReason = 18
	ErrorReason_ConfigureVersionExistError  ErrorReason = 19
	ErrorReason_WatchConfigureError         ErrorReason = 20
	ErrorReason_TokenAuthError              ErrorReason = 21
	ErrorReason_ServerNotFound              ErrorReason = 22
	ErrorReason_PasswordError               ErrorReason = 23
	ErrorReason_PasswordExpireError         ErrorReason = 24
	ErrorReason_RefreshTokenError           ErrorReason = 25
	ErrorReason_SystemError                 ErrorReason = 26
	ErrorReason_ManagerServerError          ErrorReason = 27
	ErrorReason_NotPermissionError          ErrorReason = 28
	ErrorReason_BroadcastConfigureError     ErrorReason = 29
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "ParamsError",
		1:  "DatabaseError",
		2:  "TransformError",
		3:  "GetError",
		4:  "ListError",
		5:  "CreateError",
		6:  "ImportError",
		7:  "ExportError",
		8:  "UpdateError",
		9:  "DeleteError",
		10: "GetTrashError",
		11: "ListTrashError",
		12: "DeleteTrashError",
		13: "RevertTrashError",
		14: "BusinessValueTypeError",
		15: "ResourceValueTypeError",
		16: "RenderTemplateError",
		17: "TemplateVersionExistError",
		18: "ServerNotExistTemplateError",
		19: "ConfigureVersionExistError",
		20: "WatchConfigureError",
		21: "TokenAuthError",
		22: "ServerNotFound",
		23: "PasswordError",
		24: "PasswordExpireError",
		25: "RefreshTokenError",
		26: "SystemError",
		27: "ManagerServerError",
		28: "NotPermissionError",
		29: "BroadcastConfigureError",
	}
	ErrorReason_value = map[string]int32{
		"ParamsError":                 0,
		"DatabaseError":               1,
		"TransformError":              2,
		"GetError":                    3,
		"ListError":                   4,
		"CreateError":                 5,
		"ImportError":                 6,
		"ExportError":                 7,
		"UpdateError":                 8,
		"DeleteError":                 9,
		"GetTrashError":               10,
		"ListTrashError":              11,
		"DeleteTrashError":            12,
		"RevertTrashError":            13,
		"BusinessValueTypeError":      14,
		"ResourceValueTypeError":      15,
		"RenderTemplateError":         16,
		"TemplateVersionExistError":   17,
		"ServerNotExistTemplateError": 18,
		"ConfigureVersionExistError":  19,
		"WatchConfigureError":         20,
		"TokenAuthError":              21,
		"ServerNotFound":              22,
		"PasswordError":               23,
		"PasswordExpireError":         24,
		"RefreshTokenError":           25,
		"SystemError":                 26,
		"ManagerServerError":          27,
		"NotPermissionError":          28,
		"BroadcastConfigureError":     29,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_configure_errors_configure_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_configure_errors_configure_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_configure_errors_configure_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_api_configure_errors_configure_error_reason_proto protoreflect.FileDescriptor

const file_api_configure_errors_configure_error_reason_proto_rawDesc = "" +
	"\n" +
	"1api/configure/errors/configure_error_reason.proto\x12\x06errors\x1a\x13errors/errors.proto*\xae\v\n" +
	"\vErrorReason\x12 \n" +
	"\vParamsError\x10\x00\x1a\x0f\xb2E\f参数错误\x12%\n" +
	"\rDatabaseError\x10\x01\x1a\x12\xb2E\x0f数据库错误\x12)\n" +
	"\x0eTransformError\x10\x02\x1a\x15\xb2E\x12数据转换失败\x12#\n" +
	"\bGetError\x10\x03\x1a\x15\xb2E\x12获取数据失败\x12*\n" +
	"\tListError\x10\x04\x1a\x1b\xb2E\x18获取列表数据失败\x12&\n" +
	"\vCreateError\x10\x05\x1a\x15\xb2E\x12创建数据失败\x12&\n" +
	"\vImportError\x10\x06\x1a\x15\xb2E\x12导入数据失败\x12&\n" +
	"\vExportError\x10\a\x1a\x15\xb2E\x12导出数据失败\x12&\n" +
	"\vUpdateError\x10\b\x1a\x15\xb2E\x12更新数据失败\x12&\n" +
	"\vDeleteError\x10\t\x1a\x15\xb2E\x12删除数据失败\x121\n" +
	"\rGetTrashError\x10\n" +
	"\x1a\x1e\xb2E\x1b获取回收站数据失败\x128\n" +
	"\x0eListTrashError\x10\v\x1a$\xb2E!获取回收站列表数据失败\x124\n" +
	"\x10DeleteTrashError\x10\f\x1a\x1e\xb2E\x1b删除回收站数据失败\x124\n" +
	"\x10RevertTrashError\x10\r\x1a\x1e\xb2E\x1b还原回收站数据失败\x12:\n" +
	"\x16BusinessValueTypeError\x10\x0e\x1a\x1e\xb2E\x1b业务配置值类型错误\x12:\n" +
	"\x16ResourceValueTypeError\x10\x0f\x1a\x1e\xb2E\x1b资源配置值类型错误\x12.\n" +
	"\x13RenderTemplateError\x10\x10\x1a\x15\xb2E\x12渲染模板错误\x12:\n" +
	"\x19TemplateVersionExistError\x10\x11\x1a\x1b\xb2E\x18模板已存在此版本\x12E\n" +
	"\x1bServerNotExistTemplateError\x10\x12\x1a$\xb2E!当前服务还未提交过模板\x12;\n" +
	"\x1aConfigureVersionExistError\x10\x13\x1a\x1b\xb2E\x18配置已存在此版本\x124\n" +
	"\x13WatchConfigureError\x10\x14\x1a\x1b\xb2E\x18监听版本更新失败\x12(\n" +
	"\x0eTokenAuthError\x10\x15\x1a\x14\xb2E\x11token验证失败\x12&\n" +
	"\x0eServerNotFound\x10\x16\x1a\x12\xb2E\x0f服务不存在\x12\"\n" +
	"\rPasswordError\x10\x17\x1a\x0f\xb2E\f密码错误\x12+\n" +
	"\x13PasswordExpireError\x10\x18\x1a\x12\xb2E\x0f密码已过期\x12/\n" +
	"\x11RefreshTokenError\x10\x19\x1a\x18\xa8E\x91\x03\xb2E\x11刷新token失败\x12 \n" +
	"\vSystemError\x10\x1a\x1a\x0f\xb2E\f系统错误\x123\n" +
	"\x12ManagerServerError\x10\x1b\x1a\x1b\xb2E\x18管理中心服务异常\x12*\n" +
	"\x12NotPermissionError\x10\x1c\x1a\x12\xb2E\x0f无资源权限\x12>\n" +
	"\x17BroadcastConfigureError\x10\x1d\x1a!\xb2E\x1e广播配置变更消息失败\x1a\x04\xa0E\xf4\x03B\vZ\t./;errorsb\x06proto3"

var (
	file_api_configure_errors_configure_error_reason_proto_rawDescOnce sync.Once
	file_api_configure_errors_configure_error_reason_proto_rawDescData []byte
)

func file_api_configure_errors_configure_error_reason_proto_rawDescGZIP() []byte {
	file_api_configure_errors_configure_error_reason_proto_rawDescOnce.Do(func() {
		file_api_configure_errors_configure_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_configure_errors_configure_error_reason_proto_rawDesc), len(file_api_configure_errors_configure_error_reason_proto_rawDesc)))
	})
	return file_api_configure_errors_configure_error_reason_proto_rawDescData
}

var file_api_configure_errors_configure_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_configure_errors_configure_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: errors.ErrorReason
}
var file_api_configure_errors_configure_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_configure_errors_configure_error_reason_proto_init() }
func file_api_configure_errors_configure_error_reason_proto_init() {
	if File_api_configure_errors_configure_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_configure_errors_configure_error_reason_proto_rawDesc), len(file_api_configure_errors_configure_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_configure_errors_configure_error_reason_proto_goTypes,
		DependencyIndexes: file_api_configure_errors_configure_error_reason_proto_depIdxs,
		EnumInfos:         file_api_configure_errors_configure_error_reason_proto_enumTypes,
	}.Build()
	File_api_configure_errors_configure_error_reason_proto = out.File
	file_api_configure_errors_configure_error_reason_proto_goTypes = nil
	file_api_configure_errors_configure_error_reason_proto_depIdxs = nil
}
