// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/configure/dictionary/layout_dictionary_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_configure_dictionary_layout_dictionary_service_proto protoreflect.FileDescriptor

const file_api_configure_dictionary_layout_dictionary_service_proto_rawDesc = "" +
	"\n" +
	"8api/configure/dictionary/layout_dictionary_service.proto\x12%configure.api.configure.dictionary.v1\x1a0api/configure/dictionary/layout_dictionary.proto\x1a\x1cgoogle/api/annotations.proto2\xa2\a\n" +
	"\n" +
	"Dictionary\x12\xad\x01\n" +
	"\rGetDictionary\x12;.configure.api.configure.dictionary.v1.GetDictionaryRequest\x1a9.configure.api.configure.dictionary.v1.GetDictionaryReply\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/configure/api/v1/dictionary\x12\xb2\x01\n" +
	"\x0eListDictionary\x12<.configure.api.configure.dictionary.v1.ListDictionaryRequest\x1a:.configure.api.configure.dictionary.v1.ListDictionaryReply\"&\x82\xd3\xe4\x93\x02 \x12\x1e/configure/api/v1/dictionaries\x12\xb9\x01\n" +
	"\x10CreateDictionary\x12>.configure.api.configure.dictionary.v1.CreateDictionaryRequest\x1a<.configure.api.configure.dictionary.v1.CreateDictionaryReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/configure/api/v1/dictionary\x12\xb9\x01\n" +
	"\x10UpdateDictionary\x12>.configure.api.configure.dictionary.v1.UpdateDictionaryRequest\x1a<.configure.api.configure.dictionary.v1.UpdateDictionaryReply\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/configure/api/v1/dictionary\x12\xb6\x01\n" +
	"\x10DeleteDictionary\x12>.configure.api.configure.dictionary.v1.DeleteDictionaryRequest\x1a<.configure.api.configure.dictionary.v1.DeleteDictionaryReply\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/configure/api/v1/dictionaryB@\n" +
	"%configure.api.configure.dictionary.v1B\fDictionaryV1P\x01Z\a./v1;v1b\x06proto3"

var file_api_configure_dictionary_layout_dictionary_service_proto_goTypes = []any{
	(*GetDictionaryRequest)(nil),    // 0: configure.api.configure.dictionary.v1.GetDictionaryRequest
	(*ListDictionaryRequest)(nil),   // 1: configure.api.configure.dictionary.v1.ListDictionaryRequest
	(*CreateDictionaryRequest)(nil), // 2: configure.api.configure.dictionary.v1.CreateDictionaryRequest
	(*UpdateDictionaryRequest)(nil), // 3: configure.api.configure.dictionary.v1.UpdateDictionaryRequest
	(*DeleteDictionaryRequest)(nil), // 4: configure.api.configure.dictionary.v1.DeleteDictionaryRequest
	(*GetDictionaryReply)(nil),      // 5: configure.api.configure.dictionary.v1.GetDictionaryReply
	(*ListDictionaryReply)(nil),     // 6: configure.api.configure.dictionary.v1.ListDictionaryReply
	(*CreateDictionaryReply)(nil),   // 7: configure.api.configure.dictionary.v1.CreateDictionaryReply
	(*UpdateDictionaryReply)(nil),   // 8: configure.api.configure.dictionary.v1.UpdateDictionaryReply
	(*DeleteDictionaryReply)(nil),   // 9: configure.api.configure.dictionary.v1.DeleteDictionaryReply
}
var file_api_configure_dictionary_layout_dictionary_service_proto_depIdxs = []int32{
	0, // 0: configure.api.configure.dictionary.v1.Dictionary.GetDictionary:input_type -> configure.api.configure.dictionary.v1.GetDictionaryRequest
	1, // 1: configure.api.configure.dictionary.v1.Dictionary.ListDictionary:input_type -> configure.api.configure.dictionary.v1.ListDictionaryRequest
	2, // 2: configure.api.configure.dictionary.v1.Dictionary.CreateDictionary:input_type -> configure.api.configure.dictionary.v1.CreateDictionaryRequest
	3, // 3: configure.api.configure.dictionary.v1.Dictionary.UpdateDictionary:input_type -> configure.api.configure.dictionary.v1.UpdateDictionaryRequest
	4, // 4: configure.api.configure.dictionary.v1.Dictionary.DeleteDictionary:input_type -> configure.api.configure.dictionary.v1.DeleteDictionaryRequest
	5, // 5: configure.api.configure.dictionary.v1.Dictionary.GetDictionary:output_type -> configure.api.configure.dictionary.v1.GetDictionaryReply
	6, // 6: configure.api.configure.dictionary.v1.Dictionary.ListDictionary:output_type -> configure.api.configure.dictionary.v1.ListDictionaryReply
	7, // 7: configure.api.configure.dictionary.v1.Dictionary.CreateDictionary:output_type -> configure.api.configure.dictionary.v1.CreateDictionaryReply
	8, // 8: configure.api.configure.dictionary.v1.Dictionary.UpdateDictionary:output_type -> configure.api.configure.dictionary.v1.UpdateDictionaryReply
	9, // 9: configure.api.configure.dictionary.v1.Dictionary.DeleteDictionary:output_type -> configure.api.configure.dictionary.v1.DeleteDictionaryReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_configure_dictionary_layout_dictionary_service_proto_init() }
func file_api_configure_dictionary_layout_dictionary_service_proto_init() {
	if File_api_configure_dictionary_layout_dictionary_service_proto != nil {
		return
	}
	file_api_configure_dictionary_layout_dictionary_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_configure_dictionary_layout_dictionary_service_proto_rawDesc), len(file_api_configure_dictionary_layout_dictionary_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_configure_dictionary_layout_dictionary_service_proto_goTypes,
		DependencyIndexes: file_api_configure_dictionary_layout_dictionary_service_proto_depIdxs,
	}.Build()
	File_api_configure_dictionary_layout_dictionary_service_proto = out.File
	file_api_configure_dictionary_layout_dictionary_service_proto_goTypes = nil
	file_api_configure_dictionary_layout_dictionary_service_proto_depIdxs = nil
}
