// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/configure/dictionary/layout_dictionary.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDictionaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Keyword       *string                `protobuf:"bytes,2,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDictionaryRequest) Reset() {
	*x = GetDictionaryRequest{}
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryRequest) ProtoMessage() {}

func (x *GetDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryRequest.ProtoReflect.Descriptor instead.
func (*GetDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_api_configure_dictionary_layout_dictionary_proto_rawDescGZIP(), []int{0}
}

func (x *GetDictionaryRequest) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GetDictionaryRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

type GetDictionaryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CreatedAt     uint32                 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     uint32                 `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDictionaryReply) Reset() {
	*x = GetDictionaryReply{}
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDictionaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryReply) ProtoMessage() {}

func (x *GetDictionaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryReply.ProtoReflect.Descriptor instead.
func (*GetDictionaryReply) Descriptor() ([]byte, []int) {
	return file_api_configure_dictionary_layout_dictionary_proto_rawDescGZIP(), []int{1}
}

func (x *GetDictionaryReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDictionaryReply) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetDictionaryReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDictionaryReply) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *GetDictionaryReply) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetDictionaryReply) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListDictionaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Order         *string                `protobuf:"bytes,3,opt,name=order,proto3,oneof" json:"order,omitempty"`
	OrderBy       *string                `protobuf:"bytes,4,opt,name=orderBy,proto3,oneof" json:"orderBy,omitempty"`
	Keyword       *string                `protobuf:"bytes,5,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`
	Name          *string                `protobuf:"bytes,6,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictionaryRequest) Reset() {
	*x = ListDictionaryRequest{}
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionaryRequest) ProtoMessage() {}

func (x *ListDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionaryRequest.ProtoReflect.Descriptor instead.
func (*ListDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_api_configure_dictionary_layout_dictionary_proto_rawDescGZIP(), []int{2}
}

func (x *ListDictionaryRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDictionaryRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDictionaryRequest) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

func (x *ListDictionaryRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListDictionaryRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *ListDictionaryRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type ListDictionaryReply struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Total         uint32                            `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*ListDictionaryReply_Dictionary `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictionaryReply) Reset() {
	*x = ListDictionaryReply{}
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictionaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionaryReply) ProtoMessage() {}

func (x *ListDictionaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionaryReply.ProtoReflect.Descriptor instead.
func (*ListDictionaryReply) Descriptor() ([]byte, []int) {
	return file_api_configure_dictionary_layout_dictionary_proto_rawDescGZIP(), []int{3}
}

func (x *ListDictionaryReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDictionaryReply) GetList() []*ListDictionaryReply_Dictionary {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateDictionaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDictionaryRequest) Reset() {
	*x = CreateDictionaryRequest{}
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictionaryRequest) ProtoMessage() {}

func (x *CreateDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictionaryRequest.ProtoReflect.Descriptor instead.
func (*CreateDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_api_configure_dictionary_layout_dictionary_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDictionaryRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *CreateDictionaryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDictionaryRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateDictionaryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDictionaryReply) Reset() {
	*x = CreateDictionaryReply{}
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDictionaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictionaryReply) ProtoMessage() {}

func (x *CreateDictionaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictionaryReply.ProtoReflect.Descriptor instead.
func (*CreateDictionaryReply) Descriptor() ([]byte, []int) {
	return file_api_configure_dictionary_layout_dictionary_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDictionaryReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateDictionaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDictionaryRequest) Reset() {
	*x = UpdateDictionaryRequest{}
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictionaryRequest) ProtoMessage() {}

func (x *UpdateDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictionaryRequest.ProtoReflect.Descriptor instead.
func (*UpdateDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_api_configure_dictionary_layout_dictionary_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDictionaryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDictionaryRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *UpdateDictionaryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDictionaryRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdateDictionaryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDictionaryReply) Reset() {
	*x = UpdateDictionaryReply{}
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDictionaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictionaryReply) ProtoMessage() {}

func (x *UpdateDictionaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictionaryReply.ProtoReflect.Descriptor instead.
func (*UpdateDictionaryReply) Descriptor() ([]byte, []int) {
	return file_api_configure_dictionary_layout_dictionary_proto_rawDescGZIP(), []int{7}
}

type DeleteDictionaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDictionaryRequest) Reset() {
	*x = DeleteDictionaryRequest{}
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDictionaryRequest) ProtoMessage() {}

func (x *DeleteDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDictionaryRequest.ProtoReflect.Descriptor instead.
func (*DeleteDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_api_configure_dictionary_layout_dictionary_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDictionaryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDictionaryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDictionaryReply) Reset() {
	*x = DeleteDictionaryReply{}
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDictionaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDictionaryReply) ProtoMessage() {}

func (x *DeleteDictionaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDictionaryReply.ProtoReflect.Descriptor instead.
func (*DeleteDictionaryReply) Descriptor() ([]byte, []int) {
	return file_api_configure_dictionary_layout_dictionary_proto_rawDescGZIP(), []int{9}
}

type ListDictionaryReply_Dictionary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CreatedAt     uint32                 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     uint32                 `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictionaryReply_Dictionary) Reset() {
	*x = ListDictionaryReply_Dictionary{}
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictionaryReply_Dictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionaryReply_Dictionary) ProtoMessage() {}

func (x *ListDictionaryReply_Dictionary) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_dictionary_layout_dictionary_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionaryReply_Dictionary.ProtoReflect.Descriptor instead.
func (*ListDictionaryReply_Dictionary) Descriptor() ([]byte, []int) {
	return file_api_configure_dictionary_layout_dictionary_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListDictionaryReply_Dictionary) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListDictionaryReply_Dictionary) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListDictionaryReply_Dictionary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListDictionaryReply_Dictionary) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ListDictionaryReply_Dictionary) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ListDictionaryReply_Dictionary) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_api_configure_dictionary_layout_dictionary_proto protoreflect.FileDescriptor

const file_api_configure_dictionary_layout_dictionary_proto_rawDesc = "" +
	"\n" +
	"0api/configure/dictionary/layout_dictionary.proto\x12%configure.api.configure.dictionary.v1\x1a\x17validate/validate.proto\"o\n" +
	"\x14GetDictionaryRequest\x12\x1c\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00H\x00R\x02id\x88\x01\x01\x12&\n" +
	"\akeyword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x01R\akeyword\x88\x01\x01B\x05\n" +
	"\x03_idB\n" +
	"\n" +
	"\b_keyword\"\xc5\x01\n" +
	"\x12GetDictionaryReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\rR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\rR\tupdatedAtB\x0e\n" +
	"\f_description\"\x95\x02\n" +
	"\x15ListDictionaryRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x04page\x12%\n" +
	"\bpageSize\x18\x02 \x01(\rB\t\xfaB\x06*\x04\x182 \x00R\bpageSize\x12+\n" +
	"\x05order\x18\x03 \x01(\tB\x10\xfaB\rr\vR\x03ascR\x04descH\x00R\x05order\x88\x01\x01\x12(\n" +
	"\aorderBy\x18\x04 \x01(\tB\t\xfaB\x06r\x04R\x02idH\x01R\aorderBy\x88\x01\x01\x12\x1d\n" +
	"\akeyword\x18\x05 \x01(\tH\x02R\akeyword\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x06 \x01(\tH\x03R\x04name\x88\x01\x01B\b\n" +
	"\x06_orderB\n" +
	"\n" +
	"\b_orderByB\n" +
	"\n" +
	"\b_keywordB\a\n" +
	"\x05_name\"\xc6\x02\n" +
	"\x13ListDictionaryReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12Y\n" +
	"\x04list\x18\x02 \x03(\v2E.configure.api.configure.dictionary.v1.ListDictionaryReply.DictionaryR\x04list\x1a\xbd\x01\n" +
	"\n" +
	"Dictionary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\rR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\rR\tupdatedAtB\x0e\n" +
	"\f_description\"\x90\x01\n" +
	"\x17CreateDictionaryRequest\x12!\n" +
	"\akeyword\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\akeyword\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"'\n" +
	"\x15CreateDictionaryReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xa9\x01\n" +
	"\x17UpdateDictionaryRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\x12!\n" +
	"\akeyword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\akeyword\x12\x1b\n" +
	"\x04name\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\x17\n" +
	"\x15UpdateDictionaryReply\"2\n" +
	"\x17DeleteDictionaryRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02(\x01R\x02id\"\x17\n" +
	"\x15DeleteDictionaryReplyB@\n" +
	"%configure.api.configure.dictionary.v1B\fDictionaryV1P\x01Z\a./v1;v1b\x06proto3"

var (
	file_api_configure_dictionary_layout_dictionary_proto_rawDescOnce sync.Once
	file_api_configure_dictionary_layout_dictionary_proto_rawDescData []byte
)

func file_api_configure_dictionary_layout_dictionary_proto_rawDescGZIP() []byte {
	file_api_configure_dictionary_layout_dictionary_proto_rawDescOnce.Do(func() {
		file_api_configure_dictionary_layout_dictionary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_configure_dictionary_layout_dictionary_proto_rawDesc), len(file_api_configure_dictionary_layout_dictionary_proto_rawDesc)))
	})
	return file_api_configure_dictionary_layout_dictionary_proto_rawDescData
}

var file_api_configure_dictionary_layout_dictionary_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_configure_dictionary_layout_dictionary_proto_goTypes = []any{
	(*GetDictionaryRequest)(nil),           // 0: configure.api.configure.dictionary.v1.GetDictionaryRequest
	(*GetDictionaryReply)(nil),             // 1: configure.api.configure.dictionary.v1.GetDictionaryReply
	(*ListDictionaryRequest)(nil),          // 2: configure.api.configure.dictionary.v1.ListDictionaryRequest
	(*ListDictionaryReply)(nil),            // 3: configure.api.configure.dictionary.v1.ListDictionaryReply
	(*CreateDictionaryRequest)(nil),        // 4: configure.api.configure.dictionary.v1.CreateDictionaryRequest
	(*CreateDictionaryReply)(nil),          // 5: configure.api.configure.dictionary.v1.CreateDictionaryReply
	(*UpdateDictionaryRequest)(nil),        // 6: configure.api.configure.dictionary.v1.UpdateDictionaryRequest
	(*UpdateDictionaryReply)(nil),          // 7: configure.api.configure.dictionary.v1.UpdateDictionaryReply
	(*DeleteDictionaryRequest)(nil),        // 8: configure.api.configure.dictionary.v1.DeleteDictionaryRequest
	(*DeleteDictionaryReply)(nil),          // 9: configure.api.configure.dictionary.v1.DeleteDictionaryReply
	(*ListDictionaryReply_Dictionary)(nil), // 10: configure.api.configure.dictionary.v1.ListDictionaryReply.Dictionary
}
var file_api_configure_dictionary_layout_dictionary_proto_depIdxs = []int32{
	10, // 0: configure.api.configure.dictionary.v1.ListDictionaryReply.list:type_name -> configure.api.configure.dictionary.v1.ListDictionaryReply.Dictionary
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_configure_dictionary_layout_dictionary_proto_init() }
func file_api_configure_dictionary_layout_dictionary_proto_init() {
	if File_api_configure_dictionary_layout_dictionary_proto != nil {
		return
	}
	file_api_configure_dictionary_layout_dictionary_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_configure_dictionary_layout_dictionary_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_configure_dictionary_layout_dictionary_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_configure_dictionary_layout_dictionary_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_configure_dictionary_layout_dictionary_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_configure_dictionary_layout_dictionary_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_configure_dictionary_layout_dictionary_proto_rawDesc), len(file_api_configure_dictionary_layout_dictionary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_configure_dictionary_layout_dictionary_proto_goTypes,
		DependencyIndexes: file_api_configure_dictionary_layout_dictionary_proto_depIdxs,
		MessageInfos:      file_api_configure_dictionary_layout_dictionary_proto_msgTypes,
	}.Build()
	File_api_configure_dictionary_layout_dictionary_proto = out.File
	file_api_configure_dictionary_layout_dictionary_proto_goTypes = nil
	file_api_configure_dictionary_layout_dictionary_proto_depIdxs = nil
}
