// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/configure/server/configure_server.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateServerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateServerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateServerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateServerRequestMultiError, or nil if none found.
func (m *CreateServerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateServerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetKeyword()) < 1 {
		err := CreateServerRequestValidationError{
			field:  "Keyword",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := CreateServerRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if len(errors) > 0 {
		return CreateServerRequestMultiError(errors)
	}

	return nil
}

// CreateServerRequestMultiError is an error wrapping multiple validation
// errors returned by CreateServerRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateServerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateServerRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateServerRequestMultiError) AllErrors() []error { return m }

// CreateServerRequestValidationError is the validation error returned by
// CreateServerRequest.Validate if the designated constraints aren't met.
type CreateServerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateServerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateServerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateServerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateServerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateServerRequestValidationError) ErrorName() string {
	return "CreateServerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateServerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateServerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateServerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateServerRequestValidationError{}

// Validate checks the field values on CreateServerReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateServerReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateServerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateServerReplyMultiError, or nil if none found.
func (m *CreateServerReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateServerReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreateServerReplyMultiError(errors)
	}

	return nil
}

// CreateServerReplyMultiError is an error wrapping multiple validation errors
// returned by CreateServerReply.ValidateAll() if the designated constraints
// aren't met.
type CreateServerReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateServerReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateServerReplyMultiError) AllErrors() []error { return m }

// CreateServerReplyValidationError is the validation error returned by
// CreateServerReply.Validate if the designated constraints aren't met.
type CreateServerReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateServerReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateServerReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateServerReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateServerReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateServerReplyValidationError) ErrorName() string {
	return "CreateServerReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateServerReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateServerReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateServerReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateServerReplyValidationError{}
