// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/configure/server/configure_server.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status        *bool                  `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerRequest) Reset() {
	*x = CreateServerRequest{}
	mi := &file_api_configure_server_configure_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerRequest) ProtoMessage() {}

func (x *CreateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_server_configure_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerRequest.ProtoReflect.Descriptor instead.
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return file_api_configure_server_configure_server_proto_rawDescGZIP(), []int{0}
}

func (x *CreateServerRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *CreateServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServerRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateServerRequest) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

type CreateServerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerReply) Reset() {
	*x = CreateServerReply{}
	mi := &file_api_configure_server_configure_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerReply) ProtoMessage() {}

func (x *CreateServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_configure_server_configure_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerReply.ProtoReflect.Descriptor instead.
func (*CreateServerReply) Descriptor() ([]byte, []int) {
	return file_api_configure_server_configure_server_proto_rawDescGZIP(), []int{1}
}

func (x *CreateServerReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_configure_server_configure_server_proto protoreflect.FileDescriptor

const file_api_configure_server_configure_server_proto_rawDesc = "" +
	"\n" +
	"+api/configure/server/configure_server.proto\x12!configure.api.configure.server.v1\x1a\x17validate/validate.proto\"\xb4\x01\n" +
	"\x13CreateServerRequest\x12!\n" +
	"\akeyword\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\akeyword\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\bH\x01R\x06status\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_status\"#\n" +
	"\x11CreateServerReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02idB8\n" +
	"!configure.api.configure.server.v1B\bServerV1P\x01Z\a./v1;v1b\x06proto3"

var (
	file_api_configure_server_configure_server_proto_rawDescOnce sync.Once
	file_api_configure_server_configure_server_proto_rawDescData []byte
)

func file_api_configure_server_configure_server_proto_rawDescGZIP() []byte {
	file_api_configure_server_configure_server_proto_rawDescOnce.Do(func() {
		file_api_configure_server_configure_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_configure_server_configure_server_proto_rawDesc), len(file_api_configure_server_configure_server_proto_rawDesc)))
	})
	return file_api_configure_server_configure_server_proto_rawDescData
}

var file_api_configure_server_configure_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_configure_server_configure_server_proto_goTypes = []any{
	(*CreateServerRequest)(nil), // 0: configure.api.configure.server.v1.CreateServerRequest
	(*CreateServerReply)(nil),   // 1: configure.api.configure.server.v1.CreateServerReply
}
var file_api_configure_server_configure_server_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_configure_server_configure_server_proto_init() }
func file_api_configure_server_configure_server_proto_init() {
	if File_api_configure_server_configure_server_proto != nil {
		return
	}
	file_api_configure_server_configure_server_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_configure_server_configure_server_proto_rawDesc), len(file_api_configure_server_configure_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_configure_server_configure_server_proto_goTypes,
		DependencyIndexes: file_api_configure_server_configure_server_proto_depIdxs,
		MessageInfos:      file_api_configure_server_configure_server_proto_msgTypes,
	}.Build()
	File_api_configure_server_configure_server_proto = out.File
	file_api_configure_server_configure_server_proto_goTypes = nil
	file_api_configure_server_configure_server_proto_depIdxs = nil
}
